project:
  type: website
  output-dir: docs


website:
  title: "Predicting Rental Prices"
  navbar:
    left:
      - href: about.qmd
        text: Predicting Prices

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



